2020-08-30 23:38:04,312 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-30 23:50:35,375 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-30 23:51:11,103 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-30 23:51:35,972 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-30 23:52:41,203 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-30 23:57:23,659 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 00:01:06,879 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 00:02:47,090 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 00:09:41,531 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 00:36:15,929 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:02:13,884 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:07:14,807 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:12:45,755 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:13:16,879 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:13:50,060 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-08-31 01:14:41,761 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-01 19:48:03,633 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-10 22:55:37,141 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-10 23:54:35,660 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-11 02:04:30,117 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-11 02:04:33,899 ERROR: Exception on / [GET] [in c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Abu\Desktop\git\TKB\app\main\routes.py", line 23, in index
    return render_template('index.html', title='Test', table=table, last_updated=last_updated('app/static/js'))
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Abu\Desktop\git\TKB\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\abu\desktop\git\tkb\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Abu\Desktop\git\TKB\app\templates\base.html", line 24, in template
    href=" {{ url_for('static', filename=img/favicon/favicon-32x32.png') }}">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'x32'
2020-09-11 02:05:28,722 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-11 02:06:19,814 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
2020-09-11 02:48:40,716 INFO: T7D start [in C:\Users\Abu\Desktop\git\TKB\app\__init__.py:45]
